/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDetectionRouteImport } from './routes/ai-detection'
import { Route as BehaviorRouteImport } from './routes/behavior'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ThreatIntelligenceRouteImport } from './routes/threat-intelligence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDetectionRoute = AiDetectionRouteImport.update({
  id: '/ai-detection',
  path: '/ai-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const BehaviorRoute = BehaviorRouteImport.update({
  id: '/behavior',
  path: '/behavior',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceRoute = ThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/behavior': typeof BehaviorRoute
  '/dashboard': typeof DashboardRoute
  '/endpoints': typeof EndpointsRoute
  '/incidents': typeof IncidentsRoute
  '/network': typeof NetworkRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/behavior': typeof BehaviorRoute
  '/dashboard': typeof DashboardRoute
  '/endpoints': typeof EndpointsRoute
  '/incidents': typeof IncidentsRoute
  '/network': typeof NetworkRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-detection': typeof AiDetectionRoute
  '/behavior': typeof BehaviorRoute
  '/dashboard': typeof DashboardRoute
  '/endpoints': typeof EndpointsRoute
  '/incidents': typeof IncidentsRoute
  '/network': typeof NetworkRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-detection'
    | '/behavior'
    | '/dashboard'
    | '/endpoints'
    | '/incidents'
    | '/network'
    | '/threat-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-detection'
    | '/behavior'
    | '/dashboard'
    | '/endpoints'
    | '/incidents'
    | '/network'
    | '/threat-intelligence'
  id:
    | '__root__'
    | '/'
    | '/ai-detection'
    | '/behavior'
    | '/dashboard'
    | '/endpoints'
    | '/incidents'
    | '/network'
    | '/threat-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDetectionRoute: typeof AiDetectionRoute
  BehaviorRoute: typeof BehaviorRoute
  DashboardRoute: typeof DashboardRoute
  EndpointsRoute: typeof EndpointsRoute
  IncidentsRoute: typeof IncidentsRoute
  NetworkRoute: typeof NetworkRoute
  ThreatIntelligenceRoute: typeof ThreatIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-detection': {
      id: '/ai-detection'
      path: '/ai-detection'
      fullPath: '/ai-detection'
      preLoaderRoute: typeof AiDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behavior': {
      id: '/behavior'
      path: '/behavior'
      fullPath: '/behavior'
      preLoaderRoute: typeof BehaviorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence': {
      id: '/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDetectionRoute: AiDetectionRoute,
  BehaviorRoute: BehaviorRoute,
  DashboardRoute: DashboardRoute,
  EndpointsRoute: EndpointsRoute,
  IncidentsRoute: IncidentsRoute,
  NetworkRoute: NetworkRoute,
  ThreatIntelligenceRoute: ThreatIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
